import { Injectable } from '@nestjs/common';
import * as exifr from 'exifr';

const AI_KEYWORDS = [
  'midjourney', 'dall-e', 'dalle', 'stable diffusion', 'stable-diffusion',
  'stablediffusion', 'firefly', 'leonardo', 'dreamstudio', 'craiyon',
  'deepai', 'runway', 'synthesia', 'd-id', 'nightcafe', 'artbreeder',
  'wombo', 'dream', 'civitai', 'comfyui', 'automatic1111', 'a1111',
  'fooocus', 'invokeai', 'diffusers', 'kandinsky', 'flux', 'flux.1',
  'flux-schnell', 'flux-dev', 'sdxl', 'sd 1.5', 'sd1.5', 'sd3', 'sd 3',
  'generative ai', 'generated by ai', 'ai generated', 'ai-generated',
  'created with ai', 'made with ai',
];

export interface ExifResult {
  exifData: string | null;
  aiSuspicious: boolean;
  aiReason: string | null;
  autoReject: boolean;
}

@Injectable()
export class ExifAnalysisService {
  async analyze(fileBuffer: Buffer): Promise<ExifResult> {
    try {
      const exif = await exifr.parse(fileBuffer);

      const exifData = exif ? JSON.stringify(exif, this.bigintReplacer) : null;

      if (!exif) {
        return {
          exifData: null,
          aiSuspicious: true,
          aiReason: 'Nenhum dado EXIF encontrado — imagem pode ser gerada por IA',
          autoReject: false,
        };
      }

      const exifStr = JSON.stringify(exif).toLowerCase();
      const exifKeys = Object.keys(exif).map(k => k.toLowerCase());

      for (const keyword of AI_KEYWORDS) {
        if (exifStr.includes(keyword.toLowerCase())) {
          return {
            exifData,
            aiSuspicious: true,
            aiReason: `Gerador de IA detectado no EXIF: "${keyword}"`,
            autoReject: true,
          };
        }
      }

      const exifRecord = exif as Record<string, unknown>;
      const softwareValue = (exifRecord.Software as string) || (exifRecord.software as string) || '';
      if (softwareValue && typeof softwareValue === 'string') {
        const softwareLower = softwareValue.toLowerCase();
        if (softwareLower.includes('photoshop') || softwareLower.includes('gimp') || softwareLower.includes('paint')) {
          return {
            exifData,
            aiSuspicious: true,
            aiReason: `Imagem editada com "${softwareValue}" — pode ter sido manipulada`,
            autoReject: false,
          };
        }
      }

      return {
        exifData,
        aiSuspicious: false,
        aiReason: null,
        autoReject: false,
      };
    } catch (error) {
      return {
        exifData: null,
        aiSuspicious: true,
        aiReason: `Falha ao processar EXIF: ${(error as Error).message}`,
        autoReject: false,
      };
    }
  }

  private bigintReplacer(_key: string, value: unknown): unknown {
    return typeof value === 'bigint' ? value.toString() : value;
  }
}
