/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeServicoRouteImport } from './routes/termos-de-servico'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ComoUsarRouteImport } from './routes/como-usar'
import { Route as BugReportRouteImport } from './routes/bug-report'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthProfileRouteImport } from './routes/_auth/profile'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthFightersIndexRouteImport } from './routes/_auth/fighters/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin/admin/index'
import { Route as AuthReportsNewRouteImport } from './routes/_auth/reports/new'
import { Route as AuthReportsIdRouteImport } from './routes/_auth/reports/$id'
import { Route as AuthFightersIdRouteImport } from './routes/_auth/fighters/$id'
import { Route as AdminAdminFlaggedRouteImport } from './routes/_admin/admin/flagged'

const TermosDeServicoRoute = TermosDeServicoRouteImport.update({
  id: '/termos-de-servico',
  path: '/termos-de-servico',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoUsarRoute = ComoUsarRouteImport.update({
  id: '/como-usar',
  path: '/como-usar',
  getParentRoute: () => rootRouteImport,
} as any)
const BugReportRoute = BugReportRouteImport.update({
  id: '/bug-report',
  path: '/bug-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthProfileRoute = AuthProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFightersIndexRoute = AuthFightersIndexRouteImport.update({
  id: '/fighters/',
  path: '/fighters/',
  getParentRoute: () => AuthRoute,
} as any)
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AuthReportsNewRoute = AuthReportsNewRouteImport.update({
  id: '/reports/new',
  path: '/reports/new',
  getParentRoute: () => AuthRoute,
} as any)
const AuthReportsIdRoute = AuthReportsIdRouteImport.update({
  id: '/reports/$id',
  path: '/reports/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AuthFightersIdRoute = AuthFightersIdRouteImport.update({
  id: '/fighters/$id',
  path: '/fighters/$id',
  getParentRoute: () => AuthRoute,
} as any)
const AdminAdminFlaggedRoute = AdminAdminFlaggedRouteImport.update({
  id: '/admin/flagged',
  path: '/admin/flagged',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bug-report': typeof BugReportRoute
  '/como-usar': typeof ComoUsarRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/register': typeof RegisterRoute
  '/termos-de-servico': typeof TermosDeServicoRoute
  '/dashboard': typeof AuthDashboardRoute
  '/profile': typeof AuthProfileRoute
  '/admin/flagged': typeof AdminAdminFlaggedRoute
  '/fighters/$id': typeof AuthFightersIdRoute
  '/reports/$id': typeof AuthReportsIdRoute
  '/reports/new': typeof AuthReportsNewRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/fighters/': typeof AuthFightersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bug-report': typeof BugReportRoute
  '/como-usar': typeof ComoUsarRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/register': typeof RegisterRoute
  '/termos-de-servico': typeof TermosDeServicoRoute
  '/dashboard': typeof AuthDashboardRoute
  '/profile': typeof AuthProfileRoute
  '/admin/flagged': typeof AdminAdminFlaggedRoute
  '/fighters/$id': typeof AuthFightersIdRoute
  '/reports/$id': typeof AuthReportsIdRoute
  '/reports/new': typeof AuthReportsNewRoute
  '/admin': typeof AdminAdminIndexRoute
  '/fighters': typeof AuthFightersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/bug-report': typeof BugReportRoute
  '/como-usar': typeof ComoUsarRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/register': typeof RegisterRoute
  '/termos-de-servico': typeof TermosDeServicoRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_admin/admin/flagged': typeof AdminAdminFlaggedRoute
  '/_auth/fighters/$id': typeof AuthFightersIdRoute
  '/_auth/reports/$id': typeof AuthReportsIdRoute
  '/_auth/reports/new': typeof AuthReportsNewRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_auth/fighters/': typeof AuthFightersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/bug-report'
    | '/como-usar'
    | '/login'
    | '/privacidade'
    | '/register'
    | '/termos-de-servico'
    | '/dashboard'
    | '/profile'
    | '/admin/flagged'
    | '/fighters/$id'
    | '/reports/$id'
    | '/reports/new'
    | '/admin/'
    | '/fighters/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bug-report'
    | '/como-usar'
    | '/login'
    | '/privacidade'
    | '/register'
    | '/termos-de-servico'
    | '/dashboard'
    | '/profile'
    | '/admin/flagged'
    | '/fighters/$id'
    | '/reports/$id'
    | '/reports/new'
    | '/admin'
    | '/fighters'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_auth'
    | '/bug-report'
    | '/como-usar'
    | '/login'
    | '/privacidade'
    | '/register'
    | '/termos-de-servico'
    | '/_auth/dashboard'
    | '/_auth/profile'
    | '/_admin/admin/flagged'
    | '/_auth/fighters/$id'
    | '/_auth/reports/$id'
    | '/_auth/reports/new'
    | '/_admin/admin/'
    | '/_auth/fighters/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  BugReportRoute: typeof BugReportRoute
  ComoUsarRoute: typeof ComoUsarRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  RegisterRoute: typeof RegisterRoute
  TermosDeServicoRoute: typeof TermosDeServicoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-servico': {
      id: '/termos-de-servico'
      path: '/termos-de-servico'
      fullPath: '/termos-de-servico'
      preLoaderRoute: typeof TermosDeServicoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-usar': {
      id: '/como-usar'
      path: '/como-usar'
      fullPath: '/como-usar'
      preLoaderRoute: typeof ComoUsarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bug-report': {
      id: '/bug-report'
      path: '/bug-report'
      fullPath: '/bug-report'
      preLoaderRoute: typeof BugReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fighters/': {
      id: '/_auth/fighters/'
      path: '/fighters'
      fullPath: '/fighters/'
      preLoaderRoute: typeof AuthFightersIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_auth/reports/new': {
      id: '/_auth/reports/new'
      path: '/reports/new'
      fullPath: '/reports/new'
      preLoaderRoute: typeof AuthReportsNewRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reports/$id': {
      id: '/_auth/reports/$id'
      path: '/reports/$id'
      fullPath: '/reports/$id'
      preLoaderRoute: typeof AuthReportsIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/fighters/$id': {
      id: '/_auth/fighters/$id'
      path: '/fighters/$id'
      fullPath: '/fighters/$id'
      preLoaderRoute: typeof AuthFightersIdRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_admin/admin/flagged': {
      id: '/_admin/admin/flagged'
      path: '/admin/flagged'
      fullPath: '/admin/flagged'
      preLoaderRoute: typeof AdminAdminFlaggedRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminFlaggedRoute: typeof AdminAdminFlaggedRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminFlaggedRoute: AdminAdminFlaggedRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthFightersIdRoute: typeof AuthFightersIdRoute
  AuthReportsIdRoute: typeof AuthReportsIdRoute
  AuthReportsNewRoute: typeof AuthReportsNewRoute
  AuthFightersIndexRoute: typeof AuthFightersIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthDashboardRoute: AuthDashboardRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthFightersIdRoute: AuthFightersIdRoute,
  AuthReportsIdRoute: AuthReportsIdRoute,
  AuthReportsNewRoute: AuthReportsNewRoute,
  AuthFightersIndexRoute: AuthFightersIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  BugReportRoute: BugReportRoute,
  ComoUsarRoute: ComoUsarRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  RegisterRoute: RegisterRoute,
  TermosDeServicoRoute: TermosDeServicoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
