name: Scraper Weekly

on:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  scrape-and-import:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      BUCKLER_ID: ${{ secrets.BUCKLER_ID }}
      BUCKLER_R_ID: ${{ secrets.BUCKLER_R_ID }}
      BUCKLER_PRAISE_DATE: ${{ secrets.BUCKLER_PRAISE_DATE }}
    defaults:
      run:
        working-directory: scraper

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: scraper/package-lock.json

      - run: npm ci
      - run: npx prisma generate
      - run: npx tsx src/index.ts scrape-and-import
